In [24]:
import torch
x = torch.ones(2, 1)
x.requires_grad=True
x_3 = 3*x
y = x_3+2
z = torch.mean(torch.pow(y, 2))
z_2 = torch.sum(torch.pow(y, 2))

x.register_hook(lambda grad: print(grad))
x_3.register_hook(lambda grad: print(grad))

z.backward(retain_graph=True)
y.register_hook(lambda grad: -(grad))
z_2.backward()



tensor([[5.],
        [5.]])
tensor([[15.],
        [15.]])
tensor([[-10.],
        [-10.]])
tensor([[-30.],
        [-30.]])


In [25]:
x = torch.ones(2, 1)
x.requires_grad=True
x_3 = 3*x
y = x_3+2
z = torch.mean(torch.pow(y, 2))
x.register_hook(lambda grad: print(grad))
x_3.register_hook(lambda grad: print(grad))
z.backward(retain_graph=True)


tensor([[5.],
        [5.]])
tensor([[15.],
        [15.]])


In [26]:
x = torch.ones(2, 1)
x.requires_grad=True
x_3 = 3*x
y = x_3+2
z_2 = torch.sum(torch.pow(y, 2))
x.register_hook(lambda grad: print(grad))
x_3.register_hook(lambda grad: print(grad))
y.register_hook(lambda grad: -(grad))
z_2.backward()

tensor([[-10.],
        [-10.]])
tensor([[-30.],
        [-30.]])
